### ISSUE TITLE
logger terminology

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#120]
is `_LOGGER.log(5, x)` the same as `-LOGGER.debug(x)` ?

if so can we switch to using names instead of numbers all the time?

**Comment by vreuter** [comment]
It's for when I've wanted to drop into _ultra_ debug mode :stuck_out_tongue_closed_eyes: 
It keeps ordinary debug from getting insanely cluttered but gives the extra granularity when really needed. I think I've tried to use this only/mostly in spots that are usually irrelevant and/or are called _a lot_.
https://github.com/pepkit/looper/blob/dev/looper/__init__.py#L63

**Comment by nsheff** [comment]
ah. let's just add another level, then -- `_LOGGER.ultra_debug(x)`. it's just easier to understand from a dev perspective... or maybe `_LOGGER.gab(x)`

**Comment by nsheff** [comment]
or `debug2` ?

**Comment by vreuter** [comment]
The calls are on each `Logger` instance, so the changes would need to be at the module rather than package level. We could have a function wrapping `logging.getLogger` that returns a modified `Logger` instance with a specially named method attached, and then call that function rather than `getLogger` in each module where we want the ability to call the more granular method. What do you think?
