### ISSUE TITLE
Dividing PEP 2.0 from looper interface revamp

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#234]
In light of the growing complexity of the looper revamp (e.g #38, #61, #46), and given that PEP 2.0 appears pretty stable, I'd like to hear your opinion on taking the looper pipeline interface revamp out of the next looper release so as not to hold up deploying PEP 2.0. @stolarczyk and @jpsmith5 ? 

I would propose doing an interim looper release for PEP2 compatibility. I believe the looper interface revamp will take a few months.

**Comment by stolarczyk** [comment]
while I would generally prefer to make all the format-related changes all at once, I think I see the complexity issue.. if it would postpone PEP 2.0 release this much it might be valuable to split the releases. So, I'm on board. 
Although, the separation might not be trivial at this point since the PEP 2.0 support and new pipeline interface format changes were developed concurrently. But still worth the effort, I think

**Comment by nsheff** [comment]
Well, I'm open to debate. I think most of it falls to you so the question is just how quickly you think the looper changes can be done.

If the current changes are backwards compatible, we could also just release a partial looper revamp with the pep updates. That would probably be good...

**Comment by nsheff** [comment]
we're approaching the release of both pep2 and looper now; we did punt the summarizer related updates to the next version of looper though, in #242
