### ISSUE TITLE
run: Return code when no samples are submitted

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#289]
Currently the `run` command returns `0` when no samples are submitted (see for example https://travis-ci.org/github/epigen/microtest/builds/721682599).

I guess there would be valid reasons why a call without submissions should give a good exit code (I'm thinking of a dry run of course, but other cases I guess).
Question is: is this the most common case? Should looper return a non-zero exit code unless it's a dry run for example?

**Comment by nsheff** [comment]
well, if all jobs are complete, it would submit no samples but should still return 0, right?

what exactly is your question? Is what the most common case? are you trying to ask: "Should looper return !0 when no samples are submitted?" If so, I would say: No, for the use case above. Submitting no samples doesn't necessarily indicate failure.

**Comment by afrendeiro** [comment]
Yeah I understand, but could looper distinguish between everything has been done or it is a dry run, and the remaining cases? Or are there more cases in which there is no submission and it should still return `0`?

**Comment by afrendeiro** [comment]
I can see that this could be quite a lot of logic with special cases to implement but I'm trying to understand the breadth of use cases and the expected return codes associated.

**Comment by nsheff** [comment]
well, looper knows if individual submissions succeeded.  I just had a case where I submitted 150 jobs. All but 1 succeeded -- the one that failed did so due to the cluster engine just hiccuping -- rerunning the `sbatch` command worked, but there was a split second network outage or something. in this case, it would be better to return nonzero. I suppose it could return an error exit code if *any* attempted submission failed, couldn't it?

I'd propose the following:
- if any job attempted submission but didn't, return non-zero.
- no jobs attempted submission, or if all attempted submissions occurred, return 0

dry run, and no jobs left to run both fall under "no attempted submissions" and would return 0.

**Comment by afrendeiro** [comment]
Sounds good to me.

Just to be clear, does attempting to submit also include samples that are not valid for job generation? E.g. no valid interface?

**Comment by nsheff** [comment]
> does attempting to submit also include samples that are not valid for job generation? E.g. no valid interface?

my first reaction is *yes*, that would also be an error.
