### ISSUE TITLE
Looper init piface

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#327]
It would be nice to have some kind of init function so I could `looper init piface` or something to get a generic pipeline interface file, so I don't have to remember the syntax when creating a new pipeline.

**Comment by stolarczyk** [comment]
related to  https://github.com/pepkit/pipestat/issues/4

since we often rely on jsonschema to validate YAMLs (pipeline interface, pipestat config, etc) I think it would make sense to take it a step further and write a tool that would generate a YAML template given a jsonschema. We could then simply add an `init` command to every tool that requires a config at no cost.

I was able to find a JS package that does sth like this: https://github.com/json-schema-faker/json-schema-faker, no luck with Python.

**Comment by nsheff** [comment]
that's a pretty great idea!

actually, it would probably fit within yacman. it's just a function that accepts a schema and gives back a yacattmap, which can then be written to disk if desired.
