### ISSUE TITLE
Use logmuse for logging setup

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/looper#330]
alright, I brought it back to how it was set up before, so it isn't a blocking issue. 

We will need to try to use logmuse for that in the future.

_Originally posted by @stolarczyk in https://github.com/pepkit/looper/issues/328#issuecomment-856918904_

**Comment by ayobi** [comment]
I believe logmuse is now set up. In `__init__.py` I commented out:
https://github.com/pepkit/looper/blob/7ce633327929c44829286a3204da93fb5456d398/looper/__init__.py#L42-L50
and 
https://github.com/pepkit/looper/blob/7ce633327929c44829286a3204da93fb5456d398/looper/__init__.py#L110-L115
for now since they use the same verbage as logmuse's verbosity. I added:
https://github.com/pepkit/looper/blob/7ce633327929c44829286a3204da93fb5456d398/looper/__init__.py#L135
and in `looper.py` I added:
https://github.com/pepkit/looper/blob/7ce633327929c44829286a3204da93fb5456d398/looper/__init__.py#L135
and commented out some other code that was referencing the verbosity phrase.

fea166c

**Comment by nsheff** [comment]
Great! 

Instead of commenting out, feel free to just remove any of the redundant code... I'd rather not have huge commented out code blocks of deprecated code in there; this is the benefit of version control, we can always go back to a previous commit to see old code if we need to.

**Comment by ayobi** [comment]
Yeah, I thought so about removing the code rather than commenting it out, but I was kinda doing a practice run to see how it would be. I'll clean that up tomorrow. 

Looking at the tutorial, Part 2: Add CLI Args, it only mentions those three that I listed. Looking briefly in the code I see that it focuses on those 3 as well. I'll take a deeper look tomorrow.
https://github.com/databio/logmuse/blob/1b1b712c800a71dcc8a5986b142158dd634ba208/logmuse/est.py#L45-L79
