### ISSUE TITLE
Make env CLI opt available for all subcommands

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#48]
```
Building Project
Loading PEPENV: /sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/peppy/submit_templates/default_compute_settings.yaml
Using default PEPENV. You may set environment variable PEPENV to configure environment settings.
```

But I do have a PEPENV set. `looper run` correctly finds it.

**Comment by nsheff** [comment]
this is because the `--env` is in the `run` subparser, so only `run` can get the `PEPENV`. Maybe this is intended.

https://github.com/pepkit/looper/blob/a7c25cfa1bc2cee2c49b0deabf978a559ac2b5cd/looper/looper.py#L124-L127

**Comment by armonazizi** [comment]
Was this issue ever resolved? I'm trying to run looper using a singularity container and cannot get it to work with looper summarize even though my PEPENV is set. If not, is there a way to hard code the PEPENV file so looper summarize can find it?

**Comment by vreuter** [comment]
Sorry for any trouble you had @armonazizi this is now resolved in a minor branch of the `peppy` project and will make its way into the next release.

**Comment by nsheff** [comment]
@armonazizi Why would you need `looper summarize` to know the PEPENV?

And why would you run `looper summarize` in a singularity container?

I think this is bringing up a different issue.

**Comment by armonazizi** [comment]
@vreuter Thank You. I'll be sure to look for it in the next release.

@nsheff The reason I'm trying to run `looper summarize` in a container is because it requires dependancies that I was not able to install locally (Running on stanford sherlock so I have limited privileges). More specifically, I'm running the PEPATAC pipeline. I'm able to use `looper run` to perform the initial analysis, but from what I understand, I need to run the summarize function to generate QC plots and html reports. For the PEPATAC pipeline, the summarize function requires some R libraries and other dependencies that are in the PEPATAC docker/singularity container. So, it seems like I would need to run summarize in the singularity container unless I install everything locally which I have not been able to do. I'm still trying to figure out if there's a workaround but if you have any suggestions, please let me know.

Thanks for your help!

**Comment by nsheff** [comment]
@armonazizi  What you're running into is actually Issue #31. We didn't design the singularity container to be able to run the `summarize` function. We don't really have a solution -- at the moment, most `summarize` commands require fairly minimal requirements, so we just recommend installing those requirements natively.

The `Project` function comes from [pepr](https://github.com/pepkit/pepr). This is probably one of the problems. Try installing that R package and see if it helps.


The `Error in FUN(X[[i]], ...) : could not find function "startsWith"` looks like it's due to an old version of R (that function appears in base R in version 3.3, apparently). So, updating R could solve this problem.

In the long term, we will come up with a universal solution to #31, which would solve this issue.

**Comment by nsheff** [comment]
We should actually just solve this specifically for PEPATAC like this: https://github.com/databio/pepatac/issues/74

**Comment by nsheff** [comment]
@armonazizi can you try the new container (see https://github.com/databio/pepatac/issues/74) ?

**Comment by nsheff** [comment]
Back to the original issue: the `env` option should be moved into the root parser.
